name: kendra-retriever-samples
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain>=0.0.326
    - boto3>=1.28.27
    - openai
    - anthropic
    - streamlit
